project:
  name: quickstart-sample-project
  owner: quickstart@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-southeast-1
  - ap-southeast-2
  - eu-central-1
  - eu-west-1
  - sa-east-1
  - us-east-1
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  sample:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ByteValue: 1
      PasswordA: $[taskcat_genpass_8A]
      PasswordB: $[taskcat_genpass_32S]
      RandomNumber: $[taskcat_random-numbers]
      RandomString: $[taskcat_random-string]
      StackName: TestStack
      UUID: $[taskcat_genuuid]
      Param1: 'Inputs to Stack'
    regions:
    - us-east-1
    s3_bucket: ''
    template: templates/sample-yaml.template
